---
abstract: Leonardo Pisano a.k.a. Fibonacci
author:
  - 'G. Casati <fibo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-FIBO
no_index:
  directory:
    - t
    - inc
requires:
  App::Cpanminus: 1.5019
  Config::YAML: 1.42
  File::HomeDir: 1.00
  List::Util: 1.25
  Mojolicious: 3
  Moose: 2.0604
  Path::Class: 0.29
  Perl::Critic: 1.118
  Perl::Tidy: 20121207
  Scalar::Util: 1.25
  Test::More: 0.98
version: 0.01_01
