---
abstract: "Leonardo Pisano a.k.a. Fibonacci\r"
author:
  - 'G. Casati <fibo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-FIBO
requires:
  App::cpanminus: 1.5019
  CPAN: 2.00
  DBI: 1.623
  DBIx::Class: 0.08200
  DBIx::Class::Schema::Loader: 0.07033
  Dist::Zilla: 4.300028
  Dist::Zilla::MintingProfile::Author::FIBO: 0
  File::HomeDir: 1.00
  List::MoreUtils: 0.33
  List::Util: 1.25
  Mojolicious: 3.70
  Moose: 2.0604
  MooseX::App: 1.09
  MooseX::ClassAttribute: 0.26
  MooseX::Types::Path::Class: 0.06
  MooseX::Types::Structured: 0.28
  Path::Class: 0.29
  Perl::Critic: 1.118
  Perl::Critic::Bangs: 1.10
  Perl::Tidy: 20121207
  Scalar::Util: 1.25
  Test::More: 0.98
  Test::use::ok: 0.11
  Throwable::Error: 0.102080
  YAML: 0.84
  boolean: 0.28
version: 0.004
