---
abstract: 'Leonardo Pisano a.k.a. Fibonacci'
author:
  - 'G. Casati <fibo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-BeLike-FIBO
no_index:
  directory:
    - t
    - inc
requires:
  CPAN: '2'
  ExtUtils::MakeMaker: '6.64'
  Test::Compile: '1'
  Test::More: '1'
  Test::Pod: '1'
resources:
  bugtracker: http://github.com/fibo/Task-BeLike-FIBO-pm/issues
  license: http://fibo.mit-license.org/
  repository: http://github.com/fibo/Task-BeLike-FIBO-pm
version: '0.2'
